apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-frontend
  template:
    metadata:
      labels:
        app: service-frontend
    spec:
      containers:
      - name: service-frontend
        image: 379024051677.dkr.ecr.us-east-1.amazonaws.com/repo-app:#{TAG}
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 600Mi
            cpu: 1
          requests:
            memory: 300Mi
            cpu: 500m        
      imagePullSecrets:
      - name: credential-registry
---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "elb"
spec:
  selector:
    app: service-frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
